In [21]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv("Social_Network_Ads.csv")
df.head()

    User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [ ]:
df.drop("User ID",axis=1, inplace=True)

In [14]:
x = df.drop("Purchased",axis=1)
y = df["Purchased"]
x = pd.get_dummies(x, columns=['Gender'], drop_first=True)

In [17]:
x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.3, random_state=42
)

In [11]:
df.head()

   Gender  Age  EstimatedSalary  Purchased
0    Male   19            19000          0
1    Male   35            20000          0
2  Female   26            43000          0
3  Female   27            57000          0
4    Male   19            76000          0

In [27]:
le = LabelEncoder()

for col in df.select_dtypes(include=['object']).columns:
    df[col] = le.fit_transform(df[col])

In [28]:

scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [29]:
df.head()

   Gender  Age  EstimatedSalary  Purchased
0       1   19            19000          0
1       1   35            20000          0
2       0   26            43000          0
3       0   27            57000          0
4       1   19            76000          0

In [33]:
models_dict = {
    "Logistic Regression": LogisticRegression(),
    "K-Nearest Neighbors": KNeighborsClassifier(n_neighbors=5),
    "SVM Linear": SVC(kernel = "linear"),
    "SVM polynomial": SVC(kernel = "poly", degree = 3),
    "SVM RBF": SVC(kernel = "rbf")
}

In [40]:
def evaluate_model(model, x_train, y_train, x_test, y_test):
    model.fit(x_train, y_train)
    y_pred = model.predict(x_test)

    return [
        accuracy_score(y_test, y_pred),
        precision_score(y_test, y_pred),
        recall_score(y_test, y_pred),
        f1_score(y_test, y_pred)
    ]

results = []

for name, model in models_dict.items():
    acc, prec, rec, f1 = evaluate_model(
        model, x_train, y_train, x_test, y_test
    )
    results.append([name, acc, prec, rec, f1])

In [41]:
results_df = pd.DataFrame(
    results,
    columns=[
        "Model",
        "Test Accuracy",
        "Test Precision",
        "Test Recall",
        "Test F1-Score"
    ]
)

results_df

                 Model  Test Accuracy  ...  Test Recall  Test F1-Score
0  Logistic Regression       0.858333  ...     0.680851       0.790123
1  K-Nearest Neighbors       0.916667  ...     0.893617       0.893617
2           SVM Linear       0.850000  ...     0.638298       0.769231
3       SVM polynomial       0.883333  ...     0.702128       0.825000
4              SVM RBF       0.933333  ...     0.936170       0.916667

[5 rows x 5 columns]

SVM RBF is the best model